
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 26 12:48:48 MST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 22;
  public static final int Class = 3;
  public static final int Llave_c = 29;
  public static final int Op_booleano = 25;
  public static final int Llave_a = 28;
  public static final int If = 11;
  public static final int Void = 5;
  public static final int T_dato = 8;
  public static final int Static = 4;
  public static final int Else = 12;
  public static final int Corchete_c = 31;
  public static final int Corchete_a = 30;
  public static final int While = 14;
  public static final int Division = 20;
  public static final int Int = 9;
  public static final int Cadena = 10;
  public static final int Parentesis_c = 27;
  public static final int Parentesis_a = 26;
  public static final int For = 15;
  public static final int EOF = 0;
  public static final int P_coma = 33;
  public static final int error = 1;
  public static final int Linea = 6;
  public static final int Op_atribucion = 23;
  public static final int ERROR = 36;
  public static final int Do = 13;
  public static final int Modificador = 2;
  public static final int Op_logico = 21;
  public static final int Identificador = 34;
  public static final int Resta = 18;
  public static final int Multiplicacion = 19;
  public static final int Op_incremento = 24;
  public static final int Numero = 35;
  public static final int Suma = 17;
  public static final int Main = 32;
  public static final int Igual = 16;
  public static final int Comillas = 7;
}

